ci: tweak nopanic.yaml (#525)

diff --git a/.github/workflows/nopanic.yaml b/.github/workflows/nopanic.yaml
--- a/.github/workflows/nopanic.yaml
+++ b/.github/workflows/nopanic.yaml
@@ -32,14 +32,14 @@ jobs:
       - name: Build (linux_android_with_fallback.rs)
         run: cargo build --release
       - name: Check (linux_android_with_fallback.rs)
-        run: ret=$(grep panic target/release/libgetrandom_wrapper.so; echo $?); [ $ret -eq 1 ]
+        run: (exit $( grep -c panic target/release/libgetrandom_wrapper.so ))
 
       - name: Build (linux_android.rs)
         env:
           RUSTFLAGS: -Dwarnings --cfg getrandom_backend="linux_getrandom"
         run: cargo build --release
       - name: Check (linux_android.rs)
-        run: ret=$(grep panic target/release/libgetrandom_wrapper.so; echo $?); [ $ret -eq 1 ]
+        run: (exit $( grep -c panic target/release/libgetrandom_wrapper.so ))
 
       # TODO: re-enable after https://github.com/bytecodealliance/rustix/pull/1184 is released
       # - name: Build (linux_rustix.rs)
@@ -47,31 +47,31 @@ jobs:
       #     RUSTFLAGS: -Dwarnings --cfg getrandom_backend="linux_rustix"
       #   run: cargo build --release
       # - name: Check (linux_rustix.rs)
-      #   run: ret=$(grep panic target/release/libgetrandom_wrapper.so; echo $?); [ $ret -eq 1 ]
+      #   run: (exit $( grep -c panic target/release/libgetrandom_wrapper.so ))
 
       - name: Build (rdrand.rs)
         env:
           RUSTFLAGS: -Dwarnings --cfg getrandom_backend="rdrand"
         run: cargo build --release
       - name: Check (rdrand.rs)
-        run: ret=$(grep panic target/release/libgetrandom_wrapper.so; echo $?); [ $ret -eq 1 ]
+        run: (exit $( grep -c panic target/release/libgetrandom_wrapper.so ))
 
       - name: Build (custom.rs)
         env:
           RUSTFLAGS: -Dwarnings --cfg getrandom_backend="custom"
         run: cargo build --release
       - name: Check (custom.rs)
-        run: ret=$(grep panic target/release/libgetrandom_wrapper.so; echo $?); [ $ret -eq 1 ]
+        run: (exit $( grep -c panic target/release/libgetrandom_wrapper.so ))
 
       - name: Build (wasi.rs, preview 1)
         run: cargo build --release --target wasm32-wasip1
       - name: Check (wasi.rs, preview 1)
-        run: ret=$(grep panic target/wasm32-wasip1/release/getrandom_wrapper.wasm; echo $?); [ $ret -eq 1 ]
+        run: (exit $( grep -c panic target/wasm32-wasip1/release/getrandom_wrapper.wasm ))
 
       - name: Build (wasi.rs, preview 2)
         run: cargo build --release --target wasm32-wasip2
       - name: Check (wasi.rs, preview 2)
-        run: ret=$(grep panic target/wasm32-wasip2/release/getrandom_wrapper.wasm; echo $?); [ $ret -eq 1 ]
+        run: (exit $( grep -c panic target/wasm32-wasip2/release/getrandom_wrapper.wasm ))
 
   cross:
     name: Cross
@@ -86,29 +86,29 @@ jobs:
       - uses: Swatinem/rust-cache@v2
       # TODO: use pre-compiled cross after a new (post-0.2.5) release
       - name: Install cross
-        run: cargo install cross --git https://github.com/cross-rs/cross
+        run: cargo install cross --force --git https://github.com/cross-rs/cross
 
       - name: Build (rndr.rs)
         env:
           RUSTFLAGS: -Dwarnings --cfg getrandom_backend="rndr"
         run: cross build --release --target=aarch64-unknown-linux-gnu
       - name: Check (rndr.rs)
-        run: ret=$(grep panic target/aarch64-unknown-linux-gnu/release/libgetrandom_wrapper.so; echo $?); [ $ret -eq 1 ]
+        run: (exit $( grep -c panic target/aarch64-unknown-linux-gnu/release/libgetrandom_wrapper.so ))
 
       - name: Build (getrandom.rs)
         run: cross build --release --target=x86_64-unknown-freebsd
       - name: Check (getrandom.rs)
-        run: ret=$(grep panic target/x86_64-unknown-freebsd/release/libgetrandom_wrapper.so; echo $?); [ $ret -eq 1 ]
+        run: (exit $( grep -c panic target/x86_64-unknown-freebsd/release/libgetrandom_wrapper.so ))
 
       - name: Build (netbsd.rs)
         run: cross build --release --target=x86_64-unknown-netbsd
       - name: Check (netbsd.rs)
-        run: ret=$(grep panic target/x86_64-unknown-netbsd/release/libgetrandom_wrapper.so; echo $?); [ $ret -eq 1 ]
+        run: (exit $( grep -c panic target/x86_64-unknown-netbsd/release/libgetrandom_wrapper.so ))
 
       # - name: Build (solaris.rs)
       #   run: cross build --release --target=x86_64-pc-solaris
       # - name: Check (solaris.rs)
-      #   run: ret=$(grep panic target/x86_64-pc-solaris/release/libgetrandom_wrapper.so; echo $?); [ $ret -eq 1 ]
+      #   run: (exit $( grep -c panic target/x86_64-pc-solaris/release/libgetrandom_wrapper.so ))
 
   macos:
     name: macOS
@@ -121,12 +121,9 @@ jobs:
           targets: aarch64-apple-ios
       - uses: Swatinem/rust-cache@v2
       
+      # We do not need the grep check since linker fails
+      # if `panic_nonexistent` can not be eliminated
       - name: Build (getentropy.rs)
         run: cargo build --release --target=aarch64-apple-darwin
-      - name: Check (getentropy.rs)
-        run: ret=$(grep -c panic target/aarch64-apple-darwin/release/libgetrandom_wrapper.dylib); (( $ret == 1))
-
       - name: Build (apple-other.rs)
         run: cargo build --release --target=aarch64-apple-ios
-      - name: Check (apple-other.rs)
-        run: ret=$(grep -c panic target/aarch64-apple-ios/release/libgetrandom_wrapper.dylib); (( $ret == 1))
